version: '3.9'
services:
  assignment_tracker:
    build:
      context: .
    restart: always
    volumes:
      - static_data:/vol/web

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - assignment_tracker
    volumes:
      - static_data:/vol/static
    ports:
      - "80:8080"

volumes:
  static_data: